# Generated by Django 5.0.4 on 2024-04-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_added_shopkeeper'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(max_length=100, null=True)),
                ('product_Quantity', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
